extend = { path = "../cargo-make/main.toml" }

[tasks.check]
clear = true
dependencies = ["check-debug", "check-release"]

[tasks.check-debug]
toolchain = "nightly"
command = "cargo"
args = ["check-all-features"]
install_crate = "cargo-all-features"

[tasks.check-release]
toolchain = "nightly"
command = "cargo"
args = ["check-all-features", "--release"]
install_crate = "cargo-all-features"
